- name: backlog
  color: 7ef7ef
- name: blocked
  color: fc1423
- name: bug
  color: d73a4a
- name: chore
  color: ffffff
- name: ci
  color: 0075ca
- name: dependencies
  color: 0366d6
- name: discussion
  color: b6b1f9
- name: duplicate
  color: cfd3d7
- name: feature request
  color: fcf95a
- name: github_actions
  color: "000000"
- name: invalid
  color: e4e669
- name: javascript
  color: "168700"
- name: refactor
  color: 1d637f
- name: wontfix
  color: ffffff
