nodeLinker: node-modules

packageExtensions:
  eslint-config-neon@*:
    peerDependenciesMeta:
      eslint:
        optional: true
      typescript:
        optional: true
  eslint-plugin-tailwindcss@*:
    peerDependenciesMeta:
      "@angular-eslint/template-parser":
        optional: true
      "@typescript-eslint/parser":
        optional: true
      eslint:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.5.1.cjs
