packages:
  - dash
  - docs
allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  rclone.js: true
  sharp: true
  workerd: true
overrides:
  react-is: ^19.3.0
patchedDependencies:
  waku@1.0.0-rc.1: patches/waku@1.0.0-rc.1.patch
