packages:
  - dash
  - docs

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@next/*'
  - '@opennextjs/*'
  - next
  - react
  - react-dom

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - esbuild
  - rclone.js
  - sharp
  - workerd

overrides:
  react-is: ^19.2.3

patchedDependencies:
  p-retry: patches/p-retry.patch
