packages:
  - dash
  - docs

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp

overrides:
  react-is: ^19.2.0

patchedDependencies:
  p-retry: patches/p-retry.patch
