packages:
  - dash
  - docs

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "fumadocs-*"

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp

overrides:
  react-is: ^19.1.1

patchedDependencies:
  p-retry: patches/p-retry.patch
