blank_issues_enabled: false
contact_links:
  - name: Lurkr Support
    url: https://lurkr.gg/support
    about: Please use this Discord Server to ask questions and get support about the bot. We don't offer support here.
