export const EMBED_TITLE_MAX_LENGTH = 256;
export const EMBED_DESCRIPTION_MAX_LENGTH = 4_096;

export const EMBED_FIELD_NAME_MAX_LENGTH = 256;
export const EMBED_FIELD_VALUE_MAX_LENGTH = 1_024;
export const MAX_EMBED_FIELDS = 25;

export const EMBED_AUTHOR_NAME_MAX_LENGTH = 256;
export const EMBED_FOOTER_TEXT_MAX_LENGTH = 2_048;

export const EMBED_COLOR_MAX_VALUE = 0xffffff;

export const EMBED_URL_MIN_LENGTH = 10;
export const EMBED_URL_MAX_LENGTH = 2_048;
